package org.opennms.features.vaadin.pluginmanager;

import org.opennms.features.vaadin.config.model.PluginModel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class AvailablePluginControlsPanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Button installPluginButton;

	private static final long serialVersionUID = 1L;
	
	private PluginModel pluginModel=null;
	
	private ProductDescriptorTablePanel productDescriptorTablePanel=null;
	

	public void setPluginModel(PluginModel pluginModel) {
		this.pluginModel = pluginModel;
	}


	public void setProductDescriptorTablePanel(
			ProductDescriptorTablePanel productDescriptorTablePanel) {
		this.productDescriptorTablePanel = productDescriptorTablePanel;
	}
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AvailablePluginControlsPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// installPluginButton
		installPluginButton = new Button();
		installPluginButton.setCaption("Install Selected Plugin");
		installPluginButton.setImmediate(true);
		installPluginButton.setWidth("-1px");
		installPluginButton.setHeight("-1px");
		mainLayout.addComponent(installPluginButton);
		
		return mainLayout;
	}


}
