package org.opennms.features.vaadin.pluginmanager;

import org.opennms.features.vaadin.config.model.PluginModel;
import org.opennms.karaf.licencemgr.metadata.jaxb.LicenceList;
import org.opennms.karaf.licencemgr.metadata.jaxb.ProductSpecList;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PluginManagerUIMainPanelImpl2 extends CustomComponent {



	/*- VaadinEditorProperties={"grid":"RegularGrid,5","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalSplitPanel pluginMgrHorSplitPanel_1;

	@AutoGenerated
	private VerticalLayout featureSettingsPanel;

	@AutoGenerated
	private TextArea systemMessages;

	@AutoGenerated
	private TabSheet featuresTabSheet_1;

	@AutoGenerated
	private VerticalLayout addLicenceTab;

	@AutoGenerated
	private AddLicencePanel addLicencePanel;

	@AutoGenerated
	private VerticalLayout installedLicencesTab;

	@AutoGenerated
	private LicenceDescriptorTablePanel licenceDescriptorTablePanel;

	@AutoGenerated
	private VerticalLayout availablePluginsTab;

	@AutoGenerated
	private ProductDescriptorTablePanel availablePluginsPanel;

	@AutoGenerated
	private VerticalLayout installedPluginsTab;

	@AutoGenerated
	private ProductDescriptorTablePanel installedPluginsPanel;

	@AutoGenerated
	private VerticalLayout generalSettingsPanel;

	@AutoGenerated
	private VerticalLayout rawPluginImportPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;

	@AutoGenerated
	private Button unInstallRawPluginButton;

	@AutoGenerated
	private Button installRawPluginButton;

	@AutoGenerated
	private TextField rawMavenPluginIdTxtField;

	@AutoGenerated
	private VerticalLayout featureServerPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;

	@AutoGenerated
	private Button updatePluginServerButton;

	@AutoGenerated
	private TextField featureServerPasswordTxtField;

	@AutoGenerated
	private TextField featureServerUsernameTxtField;

	@AutoGenerated
	private TextField featureServerUrlTxtField;

	@AutoGenerated
	private VerticalLayout licenceServerConfigPanel;

	@AutoGenerated
	private Button updateLicenceServerButton;

	@AutoGenerated
	private TextField licenceServerPasswordTxtField;

	@AutoGenerated
	private TextField licenceServerUsernameTxtField;

	@AutoGenerated
	private TextField licenceServerUrlTxtField;

	@AutoGenerated
	private VerticalLayout systemIdPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;

	@AutoGenerated
	private Button generateRandomSystemIdButton;

	@AutoGenerated
	private Button updateSystemIdButton;

	@AutoGenerated
	private TextField systemIdTxtField;

	private PluginModel pluginModel;

	private static final long serialVersionUID = 1L;
	

	public PluginModel getPluginModel() {
		return pluginModel;
	}

	public void setPluginModel(PluginModel pluginModel) {
		this.pluginModel = pluginModel;
	}

	

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */

	public PluginManagerUIMainPanelImpl2(PluginModel pluginModel) {
		this.pluginModel=pluginModel;
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		// added simple no effect methods to show which buttons / fields are available
		
		// General Values Panel
		
		// SystemID Panel
		generateRandomSystemIdButton.getClass();
		updateSystemIdButton.getClass();
		systemIdTxtField.setValue("System id text field");
		
		//feature server panel
		featureServerPasswordTxtField.setValue("Plugin server password");
		featureServerUsernameTxtField.setValue("Plugin server username");
		featureServerUrlTxtField.setValue("Server URL text field");
		updatePluginServerButton.getClass();
		
		// licence Server Panel
		licenceServerPasswordTxtField.setValue("Licence server password");
		licenceServerUsernameTxtField.setValue("Licence server username");
		licenceServerUrlTxtField.setValue("Licence server URL");
		updateLicenceServerButton.getClass();

		// Raw Plugin Panel
		unInstallRawPluginButton.getClass();
		installRawPluginButton.getClass();
		rawMavenPluginIdTxtField.setValue("Raw Maven command text field");
		
		
		// Plugins Detail tabs panel

		// Available Plugins Tab

		ProductSpecList availablePluginsList = pluginModel.getAvailablePlugins();
		availablePluginsPanel.addProductList(availablePluginsList);
		AvailablePluginControlsPanel  availablePluginsControlsPanel= new AvailablePluginControlsPanel();
		availablePluginsControlsPanel.setPluginModel(pluginModel);
		availablePluginsPanel.getControlsVerticalLayout().addComponent( availablePluginsControlsPanel);

		// Installed Plugins Tab
		
		ProductSpecList installedPluginsList = pluginModel.getInstalledPlugins();
		installedPluginsPanel.addProductList(installedPluginsList);
		InstalledPluginControlsPanel  installedPluginsControlsPanel= new InstalledPluginControlsPanel();
		installedPluginsControlsPanel.setPluginModel(pluginModel);
		installedPluginsPanel.getControlsVerticalLayout().addComponent( installedPluginsControlsPanel);


		// Installed Licences Tab
		LicenceList licencelist = pluginModel.getInstalledLicenceList();
		licenceDescriptorTablePanel.addLicenceList(licencelist);
		
		// Add Licences Tab
		addLicencePanel.setPluginModel(pluginModel);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// pluginMgrHorSplitPanel_1
		pluginMgrHorSplitPanel_1 = buildPluginMgrHorSplitPanel_1();
		mainLayout.addComponent(pluginMgrHorSplitPanel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildPluginMgrHorSplitPanel_1() {
		// common part: create layout
		pluginMgrHorSplitPanel_1 = new HorizontalSplitPanel();
		pluginMgrHorSplitPanel_1.setCaption("Plugin Manager Settings");
		pluginMgrHorSplitPanel_1.setImmediate(false);
		pluginMgrHorSplitPanel_1.setWidth("100.0%");
		pluginMgrHorSplitPanel_1.setHeight("100.0%");
		
		// generalSettingsPanel
		generalSettingsPanel = buildGeneralSettingsPanel();
		pluginMgrHorSplitPanel_1.addComponent(generalSettingsPanel);
		
		// featureSettingsPanel
		featureSettingsPanel = buildFeatureSettingsPanel();
		pluginMgrHorSplitPanel_1.addComponent(featureSettingsPanel);
		
		return pluginMgrHorSplitPanel_1;
	}

	@AutoGenerated
	private VerticalLayout buildGeneralSettingsPanel() {
		// common part: create layout
		generalSettingsPanel = new VerticalLayout();
		generalSettingsPanel.setCaption("General Settings");
		generalSettingsPanel.setImmediate(false);
		generalSettingsPanel.setWidth("-1px");
		generalSettingsPanel.setHeight("-1px");
		generalSettingsPanel.setMargin(true);
		
		// systemIdPanel
		systemIdPanel = buildSystemIdPanel();
		generalSettingsPanel.addComponent(systemIdPanel);
		
		// licenceServerConfigPanel
		licenceServerConfigPanel = buildLicenceServerConfigPanel();
		generalSettingsPanel.addComponent(licenceServerConfigPanel);
		
		// featureServerPanel
		featureServerPanel = buildFeatureServerPanel();
		generalSettingsPanel.addComponent(featureServerPanel);
		generalSettingsPanel.setExpandRatio(featureServerPanel, 1.0f);
		
		// rawPluginImportPanel
		rawPluginImportPanel = buildRawPluginImportPanel();
		generalSettingsPanel.addComponent(rawPluginImportPanel);
		
		return generalSettingsPanel;
	}

	@AutoGenerated
	private VerticalLayout buildSystemIdPanel() {
		// common part: create layout
		systemIdPanel = new VerticalLayout();
		systemIdPanel.setCaption("System Id Settings");
		systemIdPanel.setImmediate(false);
		systemIdPanel.setDescription("System Id Settings");
		systemIdPanel.setWidth("-1px");
		systemIdPanel.setHeight("-1px");
		systemIdPanel.setMargin(true);
		
		// systemIdTxtField
		systemIdTxtField = new TextField();
		systemIdTxtField.setCaption("System Id");
		systemIdTxtField.setImmediate(false);
		systemIdTxtField.setWidth("-1px");
		systemIdTxtField.setHeight("-1px");
		systemIdPanel.addComponent(systemIdTxtField);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		systemIdPanel.addComponent(horizontalLayout_3);
		
		return systemIdPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// updateSystemIdButton
		updateSystemIdButton = new Button();
		updateSystemIdButton.setCaption("Update System Id");
		updateSystemIdButton.setImmediate(true);
		updateSystemIdButton.setWidth("-1px");
		updateSystemIdButton.setHeight("-1px");
		horizontalLayout_3.addComponent(updateSystemIdButton);
		
		// generateRandomSystemIdButton
		generateRandomSystemIdButton = new Button();
		generateRandomSystemIdButton.setCaption("Generate Random System Id");
		generateRandomSystemIdButton.setImmediate(true);
		generateRandomSystemIdButton.setWidth("-1px");
		generateRandomSystemIdButton.setHeight("-1px");
		horizontalLayout_3.addComponent(generateRandomSystemIdButton);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildLicenceServerConfigPanel() {
		// common part: create layout
		licenceServerConfigPanel = new VerticalLayout();
		licenceServerConfigPanel.setCaption("Licence Server");
		licenceServerConfigPanel.setImmediate(false);
		licenceServerConfigPanel.setWidth("-1px");
		licenceServerConfigPanel.setHeight("-1px");
		licenceServerConfigPanel.setMargin(true);
		
		// licenceServerUrlTxtField
		licenceServerUrlTxtField = new TextField();
		licenceServerUrlTxtField.setCaption("Licence Server URL");
		licenceServerUrlTxtField.setImmediate(false);
		licenceServerUrlTxtField.setWidth("-1px");
		licenceServerUrlTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerUrlTxtField);
		
		// licenceServerUsernameTxtField
		licenceServerUsernameTxtField = new TextField();
		licenceServerUsernameTxtField.setCaption("Licence Server Username");
		licenceServerUsernameTxtField.setImmediate(false);
		licenceServerUsernameTxtField.setWidth("-1px");
		licenceServerUsernameTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerUsernameTxtField);
		
		// licenceServerPasswordTxtField
		licenceServerPasswordTxtField = new TextField();
		licenceServerPasswordTxtField.setCaption("Licence Server Password");
		licenceServerPasswordTxtField.setImmediate(false);
		licenceServerPasswordTxtField.setWidth("-1px");
		licenceServerPasswordTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerPasswordTxtField);
		
		// updateLicenceServerButton
		updateLicenceServerButton = new Button();
		updateLicenceServerButton.setCaption("Update Licence Server");
		updateLicenceServerButton.setImmediate(true);
		updateLicenceServerButton.setWidth("-1px");
		updateLicenceServerButton.setHeight("-1px");
		licenceServerConfigPanel.addComponent(updateLicenceServerButton);
		
		return licenceServerConfigPanel;
	}

	@AutoGenerated
	private VerticalLayout buildFeatureServerPanel() {
		// common part: create layout
		featureServerPanel = new VerticalLayout();
		featureServerPanel.setCaption("Maven Plugin Server");
		featureServerPanel.setImmediate(false);
		featureServerPanel.setWidth("-1px");
		featureServerPanel.setHeight("-1px");
		featureServerPanel.setMargin(true);
		
		// featureServerUrlTxtField
		featureServerUrlTxtField = new TextField();
		featureServerUrlTxtField.setCaption("Plugin Server URL");
		featureServerUrlTxtField.setImmediate(false);
		featureServerUrlTxtField.setWidth("-1px");
		featureServerUrlTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerUrlTxtField);
		
		// featureServerUsernameTxtField
		featureServerUsernameTxtField = new TextField();
		featureServerUsernameTxtField.setCaption("Plugin Server Username");
		featureServerUsernameTxtField.setImmediate(false);
		featureServerUsernameTxtField.setWidth("-1px");
		featureServerUsernameTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerUsernameTxtField);
		featureServerPanel.setExpandRatio(featureServerUsernameTxtField, 1.0f);
		
		// featureServerPasswordTxtField
		featureServerPasswordTxtField = new TextField();
		featureServerPasswordTxtField.setCaption("Plugin Server Password");
		featureServerPasswordTxtField.setImmediate(false);
		featureServerPasswordTxtField.setWidth("-1px");
		featureServerPasswordTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerPasswordTxtField);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		featureServerPanel.addComponent(horizontalLayout_2);
		
		return featureServerPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		
		// updatePluginServerButton
		updatePluginServerButton = new Button();
		updatePluginServerButton.setCaption("Update Plugin Server");
		updatePluginServerButton.setImmediate(true);
		updatePluginServerButton.setWidth("-1px");
		updatePluginServerButton.setHeight("-1px");
		horizontalLayout_2.addComponent(updatePluginServerButton);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildRawPluginImportPanel() {
		// common part: create layout
		rawPluginImportPanel = new VerticalLayout();
		rawPluginImportPanel.setCaption("Raw Plugin Import");
		rawPluginImportPanel.setImmediate(false);
		rawPluginImportPanel.setWidth("-1px");
		rawPluginImportPanel.setHeight("-1px");
		rawPluginImportPanel.setMargin(true);
		
		// rawMavenPluginIdTxtField
		rawMavenPluginIdTxtField = new TextField();
		rawMavenPluginIdTxtField.setCaption("Plugin Maven Id");
		rawMavenPluginIdTxtField.setImmediate(false);
		rawMavenPluginIdTxtField.setWidth("-1px");
		rawMavenPluginIdTxtField.setHeight("-1px");
		rawPluginImportPanel.addComponent(rawMavenPluginIdTxtField);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		rawPluginImportPanel.addComponent(horizontalLayout_6);
		
		return rawPluginImportPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(false);
		
		// installRawPluginButton
		installRawPluginButton = new Button();
		installRawPluginButton.setCaption("Install Raw Plugin");
		installRawPluginButton.setImmediate(true);
		installRawPluginButton.setWidth("-1px");
		installRawPluginButton.setHeight("-1px");
		horizontalLayout_6.addComponent(installRawPluginButton);
		
		// unInstallRawPluginButton
		unInstallRawPluginButton = new Button();
		unInstallRawPluginButton.setCaption("Uninstall Raw Plugin");
		unInstallRawPluginButton.setImmediate(true);
		unInstallRawPluginButton.setWidth("-1px");
		unInstallRawPluginButton.setHeight("-1px");
		horizontalLayout_6.addComponent(unInstallRawPluginButton);
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildFeatureSettingsPanel() {
		// common part: create layout
		featureSettingsPanel = new VerticalLayout();
		featureSettingsPanel.setCaption("Plugin Settings");
		featureSettingsPanel.setImmediate(false);
		featureSettingsPanel.setWidth("-1px");
		featureSettingsPanel.setHeight("-1px");
		featureSettingsPanel.setMargin(true);
		
		// featuresTabSheet_1
		featuresTabSheet_1 = buildFeaturesTabSheet_1();
		featureSettingsPanel.addComponent(featuresTabSheet_1);
		
		// systemMessages
		systemMessages = new TextArea();
		systemMessages.setCaption("System Messages");
		systemMessages.setImmediate(false);
		systemMessages.setWidth("100.0%");
		systemMessages.setHeight("100.0%");
		featureSettingsPanel.addComponent(systemMessages);
		
		return featureSettingsPanel;
	}

	@AutoGenerated
	private TabSheet buildFeaturesTabSheet_1() {
		// common part: create layout
		featuresTabSheet_1 = new TabSheet();
		featuresTabSheet_1.setCaption("Plugin Settings");
		featuresTabSheet_1.setImmediate(true);
		featuresTabSheet_1.setWidth("-1px");
		featuresTabSheet_1.setHeight("-1px");
		
		// installedPluginsTab
		installedPluginsTab = buildInstalledPluginsTab();
		featuresTabSheet_1.addTab(installedPluginsTab, "Installed Plugins",
				null);
		
		// availablePluginsTab
		availablePluginsTab = buildAvailablePluginsTab();
		featuresTabSheet_1.addTab(availablePluginsTab, "Available Plugins",
				null);
		
		// installedLicencesTab
		installedLicencesTab = buildInstalledLicencesTab();
		featuresTabSheet_1.addTab(installedLicencesTab, "Installed Licences",
				null);
		
		// addLicenceTab
		addLicenceTab = buildAddLicenceTab();
		featuresTabSheet_1.addTab(addLicenceTab, "Add Licence", null);
		
		return featuresTabSheet_1;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledPluginsTab() {
		// common part: create layout
		installedPluginsTab = new VerticalLayout();
		installedPluginsTab.setImmediate(false);
		installedPluginsTab.setWidth("-1px");
		installedPluginsTab.setHeight("-1px");
		installedPluginsTab.setMargin(true);
		
		// installedPluginsPanel
		installedPluginsPanel = new ProductDescriptorTablePanel();
		installedPluginsPanel.setImmediate(false);
		installedPluginsPanel.setWidth("100.0%");
		installedPluginsPanel.setHeight("100.0%");
		installedPluginsTab.addComponent(installedPluginsPanel);
		
		return installedPluginsTab;
	}

	@AutoGenerated
	private VerticalLayout buildAvailablePluginsTab() {
		// common part: create layout
		availablePluginsTab = new VerticalLayout();
		availablePluginsTab.setImmediate(false);
		availablePluginsTab.setWidth("-1px");
		availablePluginsTab.setHeight("-1px");
		availablePluginsTab.setMargin(true);
		
		// availablePluginsPanel
		availablePluginsPanel = new ProductDescriptorTablePanel();
		availablePluginsPanel.setImmediate(false);
		availablePluginsPanel.setWidth("100.0%");
		availablePluginsPanel.setHeight("100.0%");
		availablePluginsTab.addComponent(availablePluginsPanel);
		
		return availablePluginsTab;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledLicencesTab() {
		// common part: create layout
		installedLicencesTab = new VerticalLayout();
		installedLicencesTab.setCaption("Installed Licences");
		installedLicencesTab.setImmediate(false);
		installedLicencesTab.setWidth("-1px");
		installedLicencesTab.setHeight("-1px");
		installedLicencesTab.setMargin(true);
		
		// licenceDescriptorTablePanel
		licenceDescriptorTablePanel = new LicenceDescriptorTablePanel();
		licenceDescriptorTablePanel.setImmediate(false);
		licenceDescriptorTablePanel.setWidth("100.0%");
		licenceDescriptorTablePanel.setHeight("100.0%");
		installedLicencesTab.addComponent(licenceDescriptorTablePanel);
		
		return installedLicencesTab;
	}

	@AutoGenerated
	private VerticalLayout buildAddLicenceTab() {
		// common part: create layout
		addLicenceTab = new VerticalLayout();
		addLicenceTab.setCaption("Installed Licences");
		addLicenceTab.setImmediate(false);
		addLicenceTab.setWidth("-1px");
		addLicenceTab.setHeight("-1px");
		addLicenceTab.setMargin(true);
		
		// addLicencePanel
		addLicencePanel = new AddLicencePanel();
		addLicencePanel.setImmediate(false);
		addLicencePanel.setWidth("100.0%");
		addLicencePanel.setHeight("100.0%");
		addLicenceTab.addComponent(addLicencePanel);
		
		return addLicenceTab;
	}

}
