package org.opennms.features.vaadin.pluginmanager;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class ProductDescriptorPanelOld extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,5","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private TextField organizationTextField;
	@AutoGenerated
	private TextField licenceTypeTextField;
	@AutoGenerated
	private TextField licenceRequiredTextField;
	@AutoGenerated
	private TextField featureRepositoryTextArea;
	@AutoGenerated
	private TextField productUrlTextField;
	@AutoGenerated
	private TextArea productDescriptionTextField;
	@AutoGenerated
	private TextField productVersionTextField;
	@AutoGenerated
	private TextField productIdTextField;
	@AutoGenerated
	private TextField productNameTextField;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private ListSelect productListSelect;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */

	public ProductDescriptorPanelOld() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		productListSelect.removeAllItems();
		productListSelect.addItem("Mercury");
		productListSelect.addItem("Venus");
		productListSelect.addItem("Earth");
		productListSelect.addItem("Mars");
		productListSelect.addItem("Jupiter");
		productListSelect.addItem("Saturn");
		productListSelect.addItem("Neptune");
		productListSelect.addItem("Uranus");
        
        // Show 5 items and a scrollbar if there are more
        productListSelect.setRows(5);
//		
        productIdTextField.setValue("not selected");
//		
		
        // Feedback on value changes
		productListSelect.addListener(new Property.ValueChangeListener() {
            private static final long serialVersionUID = 4777915807221505438L;
            
            @Override
            public void valueChange(ValueChangeEvent event) {
            	productIdTextField.setImmediate(true);
            	productIdTextField.setValue(productListSelect.getValue().toString());
            }
        });
		
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(true);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		mainLayout.addComponent(verticalLayout_4);
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		mainLayout.addComponent(verticalLayout_5);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(true);
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(true);
		
		// productListSelect
		productListSelect = new ListSelect();
		productListSelect.setImmediate(true);
		productListSelect.setWidth("-1px");
		productListSelect.setHeight("-1px");
		verticalLayout_4.addComponent(productListSelect);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(true);
		verticalLayout_5.setWidth("-1px");
		verticalLayout_5.setHeight("-1px");
		verticalLayout_5.setMargin(true);
		
		// productNameTextField
		productNameTextField = new TextField();
		productNameTextField.setCaption("Product Name");
		productNameTextField.setImmediate(true);
		productNameTextField.setWidth("-1px");
		productNameTextField.setHeight("-1px");
		verticalLayout_5.addComponent(productNameTextField);
		
		// productIdTextField
		productIdTextField = new TextField();
		productIdTextField.setCaption("Product Id");
		productIdTextField.setImmediate(true);
		productIdTextField.setWidth("-1px");
		productIdTextField.setHeight("-1px");
		verticalLayout_5.addComponent(productIdTextField);
		
		// productVersionTextField
		productVersionTextField = new TextField();
		productVersionTextField.setCaption("Product Version");
		productVersionTextField.setImmediate(true);
		productVersionTextField.setWidth("-1px");
		productVersionTextField.setHeight("-1px");
		verticalLayout_5.addComponent(productVersionTextField);
		
		// productDescriptionTextField
		productDescriptionTextField = new TextArea();
		productDescriptionTextField.setCaption("Product Description");
		productDescriptionTextField.setImmediate(true);
		productDescriptionTextField.setWidth("-1px");
		productDescriptionTextField.setHeight("-1px");
		verticalLayout_5.addComponent(productDescriptionTextField);
		
		// productUrlTextField
		productUrlTextField = new TextField();
		productUrlTextField.setCaption("Product URL");
		productUrlTextField.setImmediate(true);
		productUrlTextField.setWidth("-1px");
		productUrlTextField.setHeight("-1px");
		verticalLayout_5.addComponent(productUrlTextField);
		
		// featureRepositoryTextArea
		featureRepositoryTextArea = new TextField();
		featureRepositoryTextArea.setCaption("Feature Repository URL");
		featureRepositoryTextArea.setImmediate(true);
		featureRepositoryTextArea.setWidth("-1px");
		featureRepositoryTextArea.setHeight("-1px");
		verticalLayout_5.addComponent(featureRepositoryTextArea);
		
		// licenceRequiredTextField
		licenceRequiredTextField = new TextField();
		licenceRequiredTextField.setCaption("Licence Required");
		licenceRequiredTextField.setImmediate(true);
		licenceRequiredTextField.setWidth("-1px");
		licenceRequiredTextField.setHeight("-1px");
		verticalLayout_5.addComponent(licenceRequiredTextField);
		
		// licenceTypeTextField
		licenceTypeTextField = new TextField();
		licenceTypeTextField.setCaption("Licence Type");
		licenceTypeTextField.setImmediate(true);
		licenceTypeTextField.setWidth("-1px");
		licenceTypeTextField.setHeight("-1px");
		licenceTypeTextField.setNullSettingAllowed(true);
		verticalLayout_5.addComponent(licenceTypeTextField);
		
		// organizationTextField
		organizationTextField = new TextField();
		organizationTextField.setCaption("Organization");
		organizationTextField.setImmediate(true);
		organizationTextField.setWidth("-1px");
		organizationTextField.setHeight("-1px");
		organizationTextField.setNullSettingAllowed(true);
		verticalLayout_5.addComponent(organizationTextField);
		
		return verticalLayout_5;
	}

}
