package org.opennms.features.vaadin.pluginmanager;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PluginManagerUIMainPanel extends CustomComponent {



	/*- VaadinEditorProperties={"grid":"RegularGrid,5","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalSplitPanel pluginMgrHorSplitPanel_1;

	@AutoGenerated
	private VerticalLayout featureSettingsPanel;

	@AutoGenerated
	private TextArea systemMessages;

	@AutoGenerated
	private TabSheet featuresTabSheet_1;

	@AutoGenerated
	private VerticalLayout installedLicencesTab;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_7;

	@AutoGenerated
	private VerticalLayout verticalLayout_4;

	@AutoGenerated
	private VerticalLayout verticalLayout_13;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_10;

	@AutoGenerated
	private Button installedLicencesTabInstallLicenceButton;

	@AutoGenerated
	private Button installedLicencesTabUninstallLicenceButton;

	@AutoGenerated
	private VerticalLayout installedLicencesTabLicenceDetailPanel;

	@AutoGenerated
	private TextArea textArea_6;

	@AutoGenerated
	private VerticalLayout verticalLayout_3;

	@AutoGenerated
	private ListSelect installedLicencesListSelect_1;

	@AutoGenerated
	private VerticalLayout installedFeaturesTab;

	@AutoGenerated
	private HorizontalLayout installedFeaturesHorizontalLayout_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_12;

	@AutoGenerated
	private VerticalLayout verticalLayout_9;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;

	@AutoGenerated
	private Button installedFeaturesTabInstallLicenceButton;

	@AutoGenerated
	private Button installedFeaturesTabUninstallLicenceButton;

	@AutoGenerated
	private VerticalLayout installedFeaturesTabLicenceDetailPanel;

	@AutoGenerated
	private TextArea textArea_2;

	@AutoGenerated
	private VerticalLayout verticalLayout_7;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_8;

	@AutoGenerated
	private Button uninstallFeatureButton;

	@AutoGenerated
	private VerticalLayout installedFeatureDetailPanel;

	@AutoGenerated
	private TextArea textArea_3;

	@AutoGenerated
	private TextField textField_12;

	@AutoGenerated
	private TextField textField_11;

	@AutoGenerated
	private VerticalLayout verticalLayout_11;

	@AutoGenerated
	private ListSelect installedFeaturesListSelect_1;

	@AutoGenerated
	private VerticalLayout availableFeaturesTab;

	@AutoGenerated
	private HorizontalLayout availableFeaturesHorizontalLayout_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_10;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;

	@AutoGenerated
	private Button installFeature_button;

	@AutoGenerated
	private VerticalLayout availableFeatureDetailPanel;

	@AutoGenerated
	private TextArea textArea_5;

	@AutoGenerated
	private TextField textField_9;

	@AutoGenerated
	private TextField textField_8;

	@AutoGenerated
	private VerticalLayout verticalLayout_6;

	@AutoGenerated
	private ListSelect availableFeaturesListSelect_1;

	@AutoGenerated
	private VerticalLayout generalSettingsPanel;

	@AutoGenerated
	private VerticalLayout rawFeatureImportPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;

	@AutoGenerated
	private Button unInstallRawFeatureButton;

	@AutoGenerated
	private Button installRawFeatureButton;

	@AutoGenerated
	private TextField rawMavenFeatureIdTxtField;

	@AutoGenerated
	private VerticalLayout featureServerPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;

	@AutoGenerated
	private Button updateFeatureServerButton;

	@AutoGenerated
	private TextField featureServerPasswordTxtField;

	@AutoGenerated
	private TextField featureServerUsernameTxtField;

	@AutoGenerated
	private TextField featureServerUrlTxtField;

	@AutoGenerated
	private VerticalLayout licenceServerConfigPanel;

	@AutoGenerated
	private Button updateLicenceServerButton;

	@AutoGenerated
	private TextField licenceServerPasswordTxtField;

	@AutoGenerated
	private TextField licenceServerUsernameTxtField;

	@AutoGenerated
	private TextField licenceServerUrlTxtField;

	@AutoGenerated
	private VerticalLayout systemIdPanel;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;

	@AutoGenerated
	private Button generateRandomSystemIdButton;

	@AutoGenerated
	private Button updateSystemIdButton;

	@AutoGenerated
	private TextField systemIdTxtField;

	private static final long serialVersionUID = 1L;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PluginManagerUIMainPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		// added simple no effect methods to show which buttons / fields are available
		
		// General Values Panel
		
		// SystemID Panel
		generateRandomSystemIdButton.getClass();
		updateSystemIdButton.getClass();
		systemIdTxtField.setValue("System id text field");
		
		//feature server panel
		featureServerPasswordTxtField.setValue("Feature server password");
		featureServerUsernameTxtField.setValue("Feature server username");
		featureServerUrlTxtField.setValue("Server URL text field");
		updateFeatureServerButton.getClass();
		
		// licence Server Panel
		licenceServerPasswordTxtField.setValue("Licence server password");
		licenceServerUsernameTxtField.setValue("Licence server username");
		licenceServerUrlTxtField.setValue("Licence server URL");
		updateLicenceServerButton.getClass();

		// Raw Feature Panel
		unInstallRawFeatureButton.getClass();
		installRawFeatureButton.getClass();
		rawMavenFeatureIdTxtField.setValue("SRaw Maven command text field");
		
		// Features Detail tabs panel

		// Available Features Tab
		availableFeaturesListSelect_1.getClass();
		availableFeatureDetailPanel.getClass();
		installFeature_button.getClass();

		// Installed Features Tab
		installedFeaturesListSelect_1.getClass();
		installedFeatureDetailPanel.getClass();
		uninstallFeatureButton.getClass();

		installedFeaturesTabLicenceDetailPanel.getClass();
		installedFeaturesTabInstallLicenceButton.getClass();
		installedFeaturesTabUninstallLicenceButton.getClass();

		// Installed Licences Tab
		installedLicencesTabLicenceDetailPanel.getClass();
		installedLicencesTabInstallLicenceButton.getClass();
		installedLicencesTabUninstallLicenceButton.getClass();

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// pluginMgrHorSplitPanel_1
		pluginMgrHorSplitPanel_1 = buildPluginMgrHorSplitPanel_1();
		mainLayout.addComponent(pluginMgrHorSplitPanel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildPluginMgrHorSplitPanel_1() {
		// common part: create layout
		pluginMgrHorSplitPanel_1 = new HorizontalSplitPanel();
		pluginMgrHorSplitPanel_1.setCaption("Plugin Manager Settings");
		pluginMgrHorSplitPanel_1.setImmediate(false);
		pluginMgrHorSplitPanel_1.setWidth("100.0%");
		pluginMgrHorSplitPanel_1.setHeight("100.0%");
		
		// generalSettingsPanel
		generalSettingsPanel = buildGeneralSettingsPanel();
		pluginMgrHorSplitPanel_1.addComponent(generalSettingsPanel);
		
		// featureSettingsPanel
		featureSettingsPanel = buildFeatureSettingsPanel();
		pluginMgrHorSplitPanel_1.addComponent(featureSettingsPanel);
		
		return pluginMgrHorSplitPanel_1;
	}

	@AutoGenerated
	private VerticalLayout buildGeneralSettingsPanel() {
		// common part: create layout
		generalSettingsPanel = new VerticalLayout();
		generalSettingsPanel.setCaption("General Settings");
		generalSettingsPanel.setImmediate(false);
		generalSettingsPanel.setWidth("-1px");
		generalSettingsPanel.setHeight("-1px");
		generalSettingsPanel.setMargin(true);
		
		// systemIdPanel
		systemIdPanel = buildSystemIdPanel();
		generalSettingsPanel.addComponent(systemIdPanel);
		
		// licenceServerConfigPanel
		licenceServerConfigPanel = buildLicenceServerConfigPanel();
		generalSettingsPanel.addComponent(licenceServerConfigPanel);
		
		// featureServerPanel
		featureServerPanel = buildFeatureServerPanel();
		generalSettingsPanel.addComponent(featureServerPanel);
		generalSettingsPanel.setExpandRatio(featureServerPanel, 1.0f);
		
		// rawFeatureImportPanel
		rawFeatureImportPanel = buildRawFeatureImportPanel();
		generalSettingsPanel.addComponent(rawFeatureImportPanel);
		
		return generalSettingsPanel;
	}

	@AutoGenerated
	private VerticalLayout buildSystemIdPanel() {
		// common part: create layout
		systemIdPanel = new VerticalLayout();
		systemIdPanel.setCaption("System Id Settings");
		systemIdPanel.setImmediate(false);
		systemIdPanel.setDescription("System Id Settings");
		systemIdPanel.setWidth("-1px");
		systemIdPanel.setHeight("-1px");
		systemIdPanel.setMargin(true);
		
		// systemIdTxtField
		systemIdTxtField = new TextField();
		systemIdTxtField.setCaption("System Id");
		systemIdTxtField.setImmediate(false);
		systemIdTxtField.setWidth("-1px");
		systemIdTxtField.setHeight("-1px");
		systemIdPanel.addComponent(systemIdTxtField);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		systemIdPanel.addComponent(horizontalLayout_3);
		
		return systemIdPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// updateSystemIdButton
		updateSystemIdButton = new Button();
		updateSystemIdButton.setCaption("Update System Id");
		updateSystemIdButton.setImmediate(true);
		updateSystemIdButton.setWidth("-1px");
		updateSystemIdButton.setHeight("-1px");
		horizontalLayout_3.addComponent(updateSystemIdButton);
		
		// generateRandomSystemIdButton
		generateRandomSystemIdButton = new Button();
		generateRandomSystemIdButton.setCaption("Generate Random System Id");
		generateRandomSystemIdButton.setImmediate(true);
		generateRandomSystemIdButton.setWidth("-1px");
		generateRandomSystemIdButton.setHeight("-1px");
		horizontalLayout_3.addComponent(generateRandomSystemIdButton);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildLicenceServerConfigPanel() {
		// common part: create layout
		licenceServerConfigPanel = new VerticalLayout();
		licenceServerConfigPanel.setCaption("Licence Server");
		licenceServerConfigPanel.setImmediate(false);
		licenceServerConfigPanel.setWidth("-1px");
		licenceServerConfigPanel.setHeight("-1px");
		licenceServerConfigPanel.setMargin(true);
		
		// licenceServerUrlTxtField
		licenceServerUrlTxtField = new TextField();
		licenceServerUrlTxtField.setCaption("Licence Server URL");
		licenceServerUrlTxtField.setImmediate(false);
		licenceServerUrlTxtField.setWidth("-1px");
		licenceServerUrlTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerUrlTxtField);
		
		// licenceServerUsernameTxtField
		licenceServerUsernameTxtField = new TextField();
		licenceServerUsernameTxtField.setCaption("Licence Server Username");
		licenceServerUsernameTxtField.setImmediate(false);
		licenceServerUsernameTxtField.setWidth("-1px");
		licenceServerUsernameTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerUsernameTxtField);
		
		// licenceServerPasswordTxtField
		licenceServerPasswordTxtField = new TextField();
		licenceServerPasswordTxtField.setCaption("Licence Server Password");
		licenceServerPasswordTxtField.setImmediate(false);
		licenceServerPasswordTxtField.setWidth("-1px");
		licenceServerPasswordTxtField.setHeight("-1px");
		licenceServerConfigPanel.addComponent(licenceServerPasswordTxtField);
		
		// updateLicenceServerButton
		updateLicenceServerButton = new Button();
		updateLicenceServerButton.setCaption("Update Licence Server");
		updateLicenceServerButton.setImmediate(true);
		updateLicenceServerButton.setWidth("-1px");
		updateLicenceServerButton.setHeight("-1px");
		licenceServerConfigPanel.addComponent(updateLicenceServerButton);
		
		return licenceServerConfigPanel;
	}

	@AutoGenerated
	private VerticalLayout buildFeatureServerPanel() {
		// common part: create layout
		featureServerPanel = new VerticalLayout();
		featureServerPanel.setCaption("Maven Feature Server");
		featureServerPanel.setImmediate(false);
		featureServerPanel.setWidth("-1px");
		featureServerPanel.setHeight("-1px");
		featureServerPanel.setMargin(true);
		
		// featureServerUrlTxtField
		featureServerUrlTxtField = new TextField();
		featureServerUrlTxtField.setCaption("Feature Server URL");
		featureServerUrlTxtField.setImmediate(false);
		featureServerUrlTxtField.setWidth("-1px");
		featureServerUrlTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerUrlTxtField);
		
		// featureServerUsernameTxtField
		featureServerUsernameTxtField = new TextField();
		featureServerUsernameTxtField.setCaption("Feature Server Username");
		featureServerUsernameTxtField.setImmediate(false);
		featureServerUsernameTxtField.setWidth("-1px");
		featureServerUsernameTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerUsernameTxtField);
		featureServerPanel.setExpandRatio(featureServerUsernameTxtField, 1.0f);
		
		// featureServerPasswordTxtField
		featureServerPasswordTxtField = new TextField();
		featureServerPasswordTxtField.setCaption("Feature Server Password");
		featureServerPasswordTxtField.setImmediate(false);
		featureServerPasswordTxtField.setWidth("-1px");
		featureServerPasswordTxtField.setHeight("-1px");
		featureServerPanel.addComponent(featureServerPasswordTxtField);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		featureServerPanel.addComponent(horizontalLayout_2);
		
		return featureServerPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		
		// updateFeatureServerButton
		updateFeatureServerButton = new Button();
		updateFeatureServerButton.setCaption("Update Feature Server");
		updateFeatureServerButton.setImmediate(true);
		updateFeatureServerButton.setWidth("-1px");
		updateFeatureServerButton.setHeight("-1px");
		horizontalLayout_2.addComponent(updateFeatureServerButton);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildRawFeatureImportPanel() {
		// common part: create layout
		rawFeatureImportPanel = new VerticalLayout();
		rawFeatureImportPanel.setCaption("Raw Feature Import");
		rawFeatureImportPanel.setImmediate(false);
		rawFeatureImportPanel.setWidth("-1px");
		rawFeatureImportPanel.setHeight("-1px");
		rawFeatureImportPanel.setMargin(true);
		
		// rawMavenFeatureIdTxtField
		rawMavenFeatureIdTxtField = new TextField();
		rawMavenFeatureIdTxtField.setCaption("Feature Maven Id");
		rawMavenFeatureIdTxtField.setImmediate(false);
		rawMavenFeatureIdTxtField.setWidth("-1px");
		rawMavenFeatureIdTxtField.setHeight("-1px");
		rawFeatureImportPanel.addComponent(rawMavenFeatureIdTxtField);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		rawFeatureImportPanel.addComponent(horizontalLayout_6);
		
		return rawFeatureImportPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(false);
		
		// installRawFeatureButton
		installRawFeatureButton = new Button();
		installRawFeatureButton.setCaption("Install Raw Feature");
		installRawFeatureButton.setImmediate(true);
		installRawFeatureButton.setWidth("-1px");
		installRawFeatureButton.setHeight("-1px");
		horizontalLayout_6.addComponent(installRawFeatureButton);
		
		// unInstallRawFeatureButton
		unInstallRawFeatureButton = new Button();
		unInstallRawFeatureButton.setCaption("Uninstall Raw Feature");
		unInstallRawFeatureButton.setImmediate(true);
		unInstallRawFeatureButton.setWidth("-1px");
		unInstallRawFeatureButton.setHeight("-1px");
		horizontalLayout_6.addComponent(unInstallRawFeatureButton);
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildFeatureSettingsPanel() {
		// common part: create layout
		featureSettingsPanel = new VerticalLayout();
		featureSettingsPanel.setCaption("Feature Settings");
		featureSettingsPanel.setImmediate(false);
		featureSettingsPanel.setWidth("-1px");
		featureSettingsPanel.setHeight("-1px");
		featureSettingsPanel.setMargin(true);
		
		// featuresTabSheet_1
		featuresTabSheet_1 = buildFeaturesTabSheet_1();
		featureSettingsPanel.addComponent(featuresTabSheet_1);
		
		// systemMessages
		systemMessages = new TextArea();
		systemMessages.setCaption("System Messages");
		systemMessages.setImmediate(false);
		systemMessages.setWidth("100.0%");
		systemMessages.setHeight("100.0%");
		featureSettingsPanel.addComponent(systemMessages);
		
		return featureSettingsPanel;
	}

	@AutoGenerated
	private TabSheet buildFeaturesTabSheet_1() {
		// common part: create layout
		featuresTabSheet_1 = new TabSheet();
		featuresTabSheet_1.setCaption("Feature Settings");
		featuresTabSheet_1.setImmediate(true);
		featuresTabSheet_1.setWidth("-1px");
		featuresTabSheet_1.setHeight("-1px");
		
		// availableFeaturesTab
		availableFeaturesTab = buildAvailableFeaturesTab();
		featuresTabSheet_1.addTab(availableFeaturesTab, "Available Features",
				null);
		
		// installedFeaturesTab
		installedFeaturesTab = buildInstalledFeaturesTab();
		featuresTabSheet_1.addTab(installedFeaturesTab, "Installed Features",
				null);
		
		// installedLicencesTab
		installedLicencesTab = buildInstalledLicencesTab();
		featuresTabSheet_1.addTab(installedLicencesTab, "Installed Licences",
				null);
		
		return featuresTabSheet_1;
	}

	@AutoGenerated
	private VerticalLayout buildAvailableFeaturesTab() {
		// common part: create layout
		availableFeaturesTab = new VerticalLayout();
		availableFeaturesTab.setCaption("Available Features");
		availableFeaturesTab.setImmediate(false);
		availableFeaturesTab.setWidth("-1px");
		availableFeaturesTab.setHeight("-1px");
		availableFeaturesTab.setMargin(true);
		
		// availableFeaturesHorizontalLayout_1
		availableFeaturesHorizontalLayout_1 = buildAvailableFeaturesHorizontalLayout_1();
		availableFeaturesTab.addComponent(availableFeaturesHorizontalLayout_1);
		
		return availableFeaturesTab;
	}

	@AutoGenerated
	private HorizontalLayout buildAvailableFeaturesHorizontalLayout_1() {
		// common part: create layout
		availableFeaturesHorizontalLayout_1 = new HorizontalLayout();
		availableFeaturesHorizontalLayout_1.setImmediate(false);
		availableFeaturesHorizontalLayout_1.setWidth("100.0%");
		availableFeaturesHorizontalLayout_1.setHeight("100.0%");
		availableFeaturesHorizontalLayout_1.setMargin(true);
		
		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		availableFeaturesHorizontalLayout_1.addComponent(verticalLayout_6);
		
		// verticalLayout_10
		verticalLayout_10 = buildVerticalLayout_10();
		availableFeaturesHorizontalLayout_1.addComponent(verticalLayout_10);
		
		return availableFeaturesHorizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("-1px");
		verticalLayout_6.setHeight("-1px");
		verticalLayout_6.setMargin(false);
		
		// availableFeaturesListSelect_1
		availableFeaturesListSelect_1 = new ListSelect();
		availableFeaturesListSelect_1.setCaption("Available Features");
		availableFeaturesListSelect_1.setImmediate(false);
		availableFeaturesListSelect_1.setWidth("-1px");
		availableFeaturesListSelect_1.setHeight("-1px");
		verticalLayout_6.addComponent(availableFeaturesListSelect_1);
		
		return verticalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_10() {
		// common part: create layout
		verticalLayout_10 = new VerticalLayout();
		verticalLayout_10.setImmediate(false);
		verticalLayout_10.setWidth("-1px");
		verticalLayout_10.setHeight("-1px");
		verticalLayout_10.setMargin(true);
		
		// availableFeatureDetailPanel
		availableFeatureDetailPanel = buildAvailableFeatureDetailPanel();
		verticalLayout_10.addComponent(availableFeatureDetailPanel);
		
		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		verticalLayout_10.addComponent(horizontalLayout_5);
		
		return verticalLayout_10;
	}

	@AutoGenerated
	private VerticalLayout buildAvailableFeatureDetailPanel() {
		// common part: create layout
		availableFeatureDetailPanel = new VerticalLayout();
		availableFeatureDetailPanel.setCaption("Feature Details");
		availableFeatureDetailPanel.setImmediate(false);
		availableFeatureDetailPanel.setWidth("-1px");
		availableFeatureDetailPanel.setHeight("-1px");
		availableFeatureDetailPanel.setMargin(true);
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setCaption("Feature Name");
		textField_8.setImmediate(false);
		textField_8.setWidth("-1px");
		textField_8.setHeight("-1px");
		availableFeatureDetailPanel.addComponent(textField_8);
		
		// textField_9
		textField_9 = new TextField();
		textField_9.setCaption("Version");
		textField_9.setImmediate(false);
		textField_9.setWidth("-1px");
		textField_9.setHeight("-1px");
		availableFeatureDetailPanel.addComponent(textField_9);
		
		// textArea_5
		textArea_5 = new TextArea();
		textArea_5.setCaption("Feature Description");
		textArea_5.setImmediate(false);
		textArea_5.setWidth("-1px");
		textArea_5.setHeight("-1px");
		availableFeatureDetailPanel.addComponent(textArea_5);
		
		return availableFeatureDetailPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setCaption("Controls");
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("-1px");
		horizontalLayout_5.setMargin(true);
		
		// installFeature_button
		installFeature_button = new Button();
		installFeature_button.setCaption("Install Feature");
		installFeature_button.setImmediate(true);
		installFeature_button
				.setDescription("Downloads and Installs the currenly selected feature");
		installFeature_button.setWidth("-1px");
		installFeature_button.setHeight("-1px");
		horizontalLayout_5.addComponent(installFeature_button);
		
		return horizontalLayout_5;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledFeaturesTab() {
		// common part: create layout
		installedFeaturesTab = new VerticalLayout();
		installedFeaturesTab.setCaption("Installed Features");
		installedFeaturesTab.setImmediate(false);
		installedFeaturesTab.setWidth("-1px");
		installedFeaturesTab.setHeight("-1px");
		installedFeaturesTab.setMargin(true);
		
		// installedFeaturesHorizontalLayout_1
		installedFeaturesHorizontalLayout_1 = buildInstalledFeaturesHorizontalLayout_1();
		installedFeaturesTab.addComponent(installedFeaturesHorizontalLayout_1);
		
		return installedFeaturesTab;
	}

	@AutoGenerated
	private HorizontalLayout buildInstalledFeaturesHorizontalLayout_1() {
		// common part: create layout
		installedFeaturesHorizontalLayout_1 = new HorizontalLayout();
		installedFeaturesHorizontalLayout_1.setImmediate(false);
		installedFeaturesHorizontalLayout_1.setWidth("-1px");
		installedFeaturesHorizontalLayout_1.setHeight("-1px");
		installedFeaturesHorizontalLayout_1.setMargin(false);
		
		// verticalLayout_11
		verticalLayout_11 = buildVerticalLayout_11();
		installedFeaturesHorizontalLayout_1.addComponent(verticalLayout_11);
		
		// verticalLayout_12
		verticalLayout_12 = buildVerticalLayout_12();
		installedFeaturesHorizontalLayout_1.addComponent(verticalLayout_12);
		
		return installedFeaturesHorizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_11() {
		// common part: create layout
		verticalLayout_11 = new VerticalLayout();
		verticalLayout_11.setImmediate(false);
		verticalLayout_11.setWidth("-1px");
		verticalLayout_11.setHeight("-1px");
		verticalLayout_11.setMargin(false);
		
		// installedFeaturesListSelect_1
		installedFeaturesListSelect_1 = new ListSelect();
		installedFeaturesListSelect_1.setCaption("Installed Features");
		installedFeaturesListSelect_1.setImmediate(false);
		installedFeaturesListSelect_1.setWidth("-1px");
		installedFeaturesListSelect_1.setHeight("-1px");
		verticalLayout_11.addComponent(installedFeaturesListSelect_1);
		
		return verticalLayout_11;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_12() {
		// common part: create layout
		verticalLayout_12 = new VerticalLayout();
		verticalLayout_12.setImmediate(false);
		verticalLayout_12.setWidth("-1px");
		verticalLayout_12.setHeight("-1px");
		verticalLayout_12.setMargin(false);
		
		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		verticalLayout_12.addComponent(verticalLayout_7);
		
		// verticalLayout_9
		verticalLayout_9 = buildVerticalLayout_9();
		verticalLayout_12.addComponent(verticalLayout_9);
		
		return verticalLayout_12;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("-1px");
		verticalLayout_7.setHeight("-1px");
		verticalLayout_7.setMargin(true);
		
		// installedFeatureDetailPanel
		installedFeatureDetailPanel = buildInstalledFeatureDetailPanel();
		verticalLayout_7.addComponent(installedFeatureDetailPanel);
		
		// horizontalLayout_8
		horizontalLayout_8 = buildHorizontalLayout_8();
		verticalLayout_7.addComponent(horizontalLayout_8);
		
		return verticalLayout_7;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledFeatureDetailPanel() {
		// common part: create layout
		installedFeatureDetailPanel = new VerticalLayout();
		installedFeatureDetailPanel.setCaption("Installed Feature Details");
		installedFeatureDetailPanel.setImmediate(false);
		installedFeatureDetailPanel.setWidth("-1px");
		installedFeatureDetailPanel.setHeight("-1px");
		installedFeatureDetailPanel.setMargin(true);
		
		// textField_11
		textField_11 = new TextField();
		textField_11.setCaption("Feature Name");
		textField_11.setImmediate(false);
		textField_11.setWidth("-1px");
		textField_11.setHeight("-1px");
		installedFeatureDetailPanel.addComponent(textField_11);
		
		// textField_12
		textField_12 = new TextField();
		textField_12.setCaption("Version");
		textField_12.setImmediate(false);
		textField_12.setWidth("-1px");
		textField_12.setHeight("-1px");
		installedFeatureDetailPanel.addComponent(textField_12);
		
		// textArea_3
		textArea_3 = new TextArea();
		textArea_3.setCaption("Feature Description");
		textArea_3.setImmediate(false);
		textArea_3.setWidth("-1px");
		textArea_3.setHeight("-1px");
		installedFeatureDetailPanel.addComponent(textArea_3);
		
		return installedFeatureDetailPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_8() {
		// common part: create layout
		horizontalLayout_8 = new HorizontalLayout();
		horizontalLayout_8.setCaption("Controls");
		horizontalLayout_8.setImmediate(false);
		horizontalLayout_8.setWidth("-1px");
		horizontalLayout_8.setHeight("-1px");
		horizontalLayout_8.setMargin(false);
		
		// uninstallFeatureButton
		uninstallFeatureButton = new Button();
		uninstallFeatureButton.setCaption("Uninstall Feature");
		uninstallFeatureButton.setImmediate(true);
		uninstallFeatureButton
				.setDescription("Uninstalls the selected feature");
		uninstallFeatureButton.setWidth("-1px");
		uninstallFeatureButton.setHeight("-1px");
		horizontalLayout_8.addComponent(uninstallFeatureButton);
		
		return horizontalLayout_8;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_9() {
		// common part: create layout
		verticalLayout_9 = new VerticalLayout();
		verticalLayout_9.setImmediate(false);
		verticalLayout_9.setWidth("-1px");
		verticalLayout_9.setHeight("-1px");
		verticalLayout_9.setMargin(false);
		
		// installedFeaturesTabLicenceDetailPanel
		installedFeaturesTabLicenceDetailPanel = buildInstalledFeaturesTabLicenceDetailPanel();
		verticalLayout_9.addComponent(installedFeaturesTabLicenceDetailPanel);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_9.addComponent(horizontalLayout_1);
		
		return verticalLayout_9;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledFeaturesTabLicenceDetailPanel() {
		// common part: create layout
		installedFeaturesTabLicenceDetailPanel = new VerticalLayout();
		installedFeaturesTabLicenceDetailPanel.setCaption("Licence Detail");
		installedFeaturesTabLicenceDetailPanel.setImmediate(false);
		installedFeaturesTabLicenceDetailPanel.setWidth("-1px");
		installedFeaturesTabLicenceDetailPanel.setHeight("-1px");
		installedFeaturesTabLicenceDetailPanel.setMargin(true);
		
		// textArea_2
		textArea_2 = new TextArea();
		textArea_2.setCaption("Licence");
		textArea_2.setImmediate(false);
		textArea_2.setWidth("-1px");
		textArea_2.setHeight("-1px");
		installedFeaturesTabLicenceDetailPanel.addComponent(textArea_2);
		
		return installedFeaturesTabLicenceDetailPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setCaption("Controls");
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// installedFeaturesTabUninstallLicenceButton
		installedFeaturesTabUninstallLicenceButton = new Button();
		installedFeaturesTabUninstallLicenceButton
				.setCaption("Uninstall Licence");
		installedFeaturesTabUninstallLicenceButton.setImmediate(true);
		installedFeaturesTabUninstallLicenceButton
				.setDescription("Uninstalls the selected feature");
		installedFeaturesTabUninstallLicenceButton.setWidth("-1px");
		installedFeaturesTabUninstallLicenceButton.setHeight("-1px");
		horizontalLayout_1
				.addComponent(installedFeaturesTabUninstallLicenceButton);
		
		// installedFeaturesTabInstallLicenceButton
		installedFeaturesTabInstallLicenceButton = new Button();
		installedFeaturesTabInstallLicenceButton.setCaption("Install Licence");
		installedFeaturesTabInstallLicenceButton.setImmediate(true);
		installedFeaturesTabInstallLicenceButton
				.setDescription("Uninstalls the selected feature");
		installedFeaturesTabInstallLicenceButton.setWidth("-1px");
		installedFeaturesTabInstallLicenceButton.setHeight("-1px");
		horizontalLayout_1
				.addComponent(installedFeaturesTabInstallLicenceButton);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledLicencesTab() {
		// common part: create layout
		installedLicencesTab = new VerticalLayout();
		installedLicencesTab.setCaption("Installed Licences");
		installedLicencesTab.setImmediate(false);
		installedLicencesTab.setWidth("-1px");
		installedLicencesTab.setHeight("-1px");
		installedLicencesTab.setMargin(true);
		
		// horizontalLayout_7
		horizontalLayout_7 = buildHorizontalLayout_7();
		installedLicencesTab.addComponent(horizontalLayout_7);
		
		return installedLicencesTab;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_7() {
		// common part: create layout
		horizontalLayout_7 = new HorizontalLayout();
		horizontalLayout_7.setImmediate(false);
		horizontalLayout_7.setWidth("-1px");
		horizontalLayout_7.setHeight("-1px");
		horizontalLayout_7.setMargin(false);
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalLayout_7.addComponent(verticalLayout_3);
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		horizontalLayout_7.addComponent(verticalLayout_4);
		
		return horizontalLayout_7;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		
		// installedLicencesListSelect_1
		installedLicencesListSelect_1 = new ListSelect();
		installedLicencesListSelect_1.setCaption("Installed Licences");
		installedLicencesListSelect_1.setImmediate(false);
		installedLicencesListSelect_1.setWidth("-1px");
		installedLicencesListSelect_1.setHeight("-1px");
		verticalLayout_3.addComponent(installedLicencesListSelect_1);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(true);
		
		// verticalLayout_13
		verticalLayout_13 = buildVerticalLayout_13();
		verticalLayout_4.addComponent(verticalLayout_13);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_13() {
		// common part: create layout
		verticalLayout_13 = new VerticalLayout();
		verticalLayout_13.setImmediate(false);
		verticalLayout_13.setWidth("-1px");
		verticalLayout_13.setHeight("-1px");
		verticalLayout_13.setMargin(false);
		
		// installedLicencesTabLicenceDetailPanel
		installedLicencesTabLicenceDetailPanel = buildInstalledLicencesTabLicenceDetailPanel();
		verticalLayout_13.addComponent(installedLicencesTabLicenceDetailPanel);
		
		// horizontalLayout_10
		horizontalLayout_10 = buildHorizontalLayout_10();
		verticalLayout_13.addComponent(horizontalLayout_10);
		
		return verticalLayout_13;
	}

	@AutoGenerated
	private VerticalLayout buildInstalledLicencesTabLicenceDetailPanel() {
		// common part: create layout
		installedLicencesTabLicenceDetailPanel = new VerticalLayout();
		installedLicencesTabLicenceDetailPanel.setCaption("Licence Detail");
		installedLicencesTabLicenceDetailPanel.setImmediate(false);
		installedLicencesTabLicenceDetailPanel.setWidth("-1px");
		installedLicencesTabLicenceDetailPanel.setHeight("-1px");
		installedLicencesTabLicenceDetailPanel.setMargin(true);
		
		// textArea_6
		textArea_6 = new TextArea();
		textArea_6.setCaption("Licence");
		textArea_6.setImmediate(false);
		textArea_6.setWidth("-1px");
		textArea_6.setHeight("-1px");
		installedLicencesTabLicenceDetailPanel.addComponent(textArea_6);
		
		return installedLicencesTabLicenceDetailPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_10() {
		// common part: create layout
		horizontalLayout_10 = new HorizontalLayout();
		horizontalLayout_10.setCaption("Controls");
		horizontalLayout_10.setImmediate(false);
		horizontalLayout_10.setWidth("-1px");
		horizontalLayout_10.setHeight("-1px");
		horizontalLayout_10.setMargin(true);
		
		// installedLicencesTabUninstallLicenceButton
		installedLicencesTabUninstallLicenceButton = new Button();
		installedLicencesTabUninstallLicenceButton
				.setCaption("Uninstall Licence");
		installedLicencesTabUninstallLicenceButton.setImmediate(true);
		installedLicencesTabUninstallLicenceButton
				.setDescription("Uninstalls the selected feature");
		installedLicencesTabUninstallLicenceButton.setWidth("-1px");
		installedLicencesTabUninstallLicenceButton.setHeight("-1px");
		horizontalLayout_10
				.addComponent(installedLicencesTabUninstallLicenceButton);
		
		// installedLicencesTabInstallLicenceButton
		installedLicencesTabInstallLicenceButton = new Button();
		installedLicencesTabInstallLicenceButton.setCaption("Install Licence");
		installedLicencesTabInstallLicenceButton.setImmediate(true);
		installedLicencesTabInstallLicenceButton
				.setDescription("Uninstalls the selected feature");
		installedLicencesTabInstallLicenceButton.setWidth("-1px");
		installedLicencesTabInstallLicenceButton.setHeight("-1px");
		horizontalLayout_10
				.addComponent(installedLicencesTabInstallLicenceButton);
		
		return horizontalLayout_10;
	}

}
